//GET ALL STUDENTS
export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_ERROR = "GET_COURSES_ERROR";

//GET SINGLE STUDENT

export const GET_SINGLE_COURSE_REQUEST = "GET_SINGLE_COURSE_REQUEST";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_ERROR = "GET_SINGLE_COURSE_ERROR";

//POST SINGLE STUDENT

export const POST_COURSE_REQUEST = "POST_COURSE_REQUEST";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_ERROR = "POST_COURSE_ERROR";

//PUT SINGLE STUDENT

export const PUT_COURSE_REQUEST = "PUT_COURSE_REQUEST";
export const PUT_COURSE_SUCCESS = "PUT_COURSE_SUCCESS";
export const PUT_COURSE_ERROR = "PUT_COURSE_ERROR";

//DELETE SINGLE STUDENT

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_ERROR = "DELETE_COURSE_ERROR";

