//GET ALL STUDENTS
export const GET_ASTUDENTS_REQUEST = "GET_ASTUDENTS_REQUEST" ;
export const GET_ASTUDENTS_SUCCESS = "GET_ASTUDENTS_SUCCESS" ;
export const GET_ASTUDENTS_ERROR   = "GET_ASTUDENTS_ERROR  " ;

//GET EDIT SINGLE STUDENT

export const GET_SINGLESTUDENT_REQUEST ="GET_SINGLESTUDENT_REQUEST";
export const GET_SINGLESTUDENT_SUCCESS ="GET_SINGLESTUDENT_SUCCESS";
export const GET_SINGLESTUDENT_ERROR   ="GET_SINGLESTUDENT_ERROR  ";

//POST SINGLE STUDENT=For Add

export const POST_ASTUDENT_REQUEST ="POST_ASTUDENT_REQUEST";
export const POST_ASTUDENT_SUCCESS ="POST_ASTUDENT_SUCCESS";
export const POST_ASTUDENT_ERROR   ="POST_ASTUDENT_ERROR "  ;

//PUT SINGLE STUDENT=For edit

export const PUT_ASTUDENT_REQUEST ="PUT_ASTUDENT_REQUEST";
export const PUT_ASTUDENT_SUCCESS ="PUT_ASTUDENT_SUCCESS";
export const PUT_ASTUDENT_ERROR   ="PUT_ASTUDENT_ERROR "    ;

//DELETE STUDENT

export const DELETE_ASTUDENT_REQUEST="DELETE_ASTUDENT_REQUEST";
export const DELETE_ASTUDENT_SUCCESS="DELETE_ASTUDENT_SUCCESS";
export const DELETE_ASTUDENT_ERROR="DELETE_ASTUDENT_ERROR";
