//GET ALL TRAINERS
export const GET_TRAINERS_REQUEST = "GET_TRAINERS_REQUEST";
export const GET_TRAINERS_SUCCESS = "GET_TRAINERS_SUCCESS";
export const GET_TRAINERS_ERROR = "GET_TRAINERS_ERROR";

//GET SINGLE TRAINER

export const GET_TRAINER_REQUEST ="GET_TRAINER_REQUEST";
export const GET_TRAINER_SUCCESS ="GET_TRAINER_SUCCESS";
export const GET_TRAINER_ERROR ="GET_TRAINER_ERROR";

//POST SINGLE TRAINER

export const POST_TRAINER_REQUEST ="POST_TRAINER_REQUEST";
export const POST_TRAINER_SUCCESS ="POST_TRAINER_SUCCESS";
export const POST_TRAINER_ERROR ="POST_TRAINER_ERROR";

//PUT SINGLE TRAINER

export const PUT_TRAINER_REQUEST ="PUT_TRAINER_REQUEST";
export const PUT_TRAINER_SUCCESS ="PUT_TRAINER_SUCCESS";
export const PUT_TRAINER_ERROR ="PUT_TRAINER_ERROR";

//DELETE SINGLE TRAINER

export const DELETE_TRAINER_REQUEST="DELETE_TRAINER_REQUEST";
export const DELETE_TRAINER_SUCCESS="DELETE_TRAINER_SUCCESS";
export const DELETE_TRAINER_ERROR="DELETE_TRAINER_ERROR";