//GET ALL HOLIDAYS
export const GET_HOLIDAYS_REQUEST = "GET_HOLIDAYS_REQUEST";
export const GET_HOLIDAYS_SUCCESS = "GET_HOLIDAYS_SUCCESS";
export const GET_HOLIDAYS_ERROR = "GET_HOLIDAYS_ERROR";

//GET SINGLE HOLIDAY

export const GET_SINGLE_HOLIDAY_REQUEST ="GET_SINGLE_HOLIDAY_REQUEST";
export const GET_SINGLE_HOLIDAY_SUCCESS ="GET_SINGLE_HOLIDAY_SUCCESS";
export const GET_SINGLE_HOLIDAY_ERROR ="GET_SINGLE_HOLIDAY_ERROR";

//POST SINGLE HOLIDAY

export const POST_HOLIDAY_REQUEST ="POST_HOLIDAY_REQUEST";
export const POST_HOLIDAY_SUCCESS ="POST_HOLIDAY_SUCCESS";
export const POST_HOLIDAY_ERROR ="POST_HOLIDAY_ERROR";

//PUT SINGLE HOLIDAY

export const PUT_HOLIDAY_REQUEST ="PUT_HOLIDAY_REQUEST";
export const PUT_HOLIDAY_SUCCESS ="PUT_HOLIDAY_SUCCESS";
export const PUT_HOLIDAY_ERROR ="PUT_HOLIDAY_ERROR";

//DELETE SINGLE TRAINER

export const DELETE_HOLIDAY_REQUEST="DELETE_HOLIDAY_REQUEST";
export const DELETE_HOLIDAY_SUCCESS="DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_ERROR="DELETE_HOLIDAY_ERROR";