//GET ALL STUDENTS
export const GET_STUDENTS_REQUEST = "STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
export const GET_STUDENTS_ERROR = "STUDENTS_ERROR";


// GET SINGLE STUDENT
export const GET_SINGLE_STUDENT_REQUEST = "GET_SINGLE_STUDENT_REQUEST";
export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_ERROR = "GET_SINGLE_STUDENT_ERROR";

// DELTE SINGLE STUDENT
export const DELETE_STUDENT_REQUEST = "STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR = "STUDENT_ERROR";


// //POST SINGLE STUDENT
export const POST_STUDENT_REQUEST = "POST_STUDENT_REQUEST";
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS";
export const POST_STUDENT_ERROR = "POST_STUDENT_ERROR";


// //PUT SINGLE STUDENT
export const PUT_STUDENT_REQUEST = "PUT_STUDENT_REQUEST";
export const PUT_STUDENT_SUCCESS = "PUT_STUDENT_SUCCESS";
export const PUT_STUDENT_ERROR = "PUT_STUDENT_ERROR";
