//GET ALL LEAVES
export const GET_LEAVES_REQUEST = "GET_LEAVES_REQUEST";
export const GET_LEAVES_SUCCESS = "GET_LEAVES_SUCCESS";
export const GET_LEAVES_ERROR = "GET_LEAVES_ERROR";

//GET SINGLE LEAVE

export const GET_SINGLE_LEAVE_REQUEST ="GET_SINGLE_LEAVE_REQUEST";
export const GET_SINGLE_LEAVE_SUCCESS ="GET_SINGLE_LEAVE_SUCCESS";
export const GET_SINGLE_LEAVE_ERROR ="GET_SINGLE_LEAVE_ERROR";

//POST SINGLE LEAVE

export const POST_LEAVE_REQUEST ="POST_LEAVE_REQUEST";
export const POST_LEAVE_SUCCESS ="POST_LEAVE_SUCCESS";
export const POST_LEAVE_ERROR ="POST_LEAVE_ERROR";

//PUT SINGLE LEAVE

export const PUT_LEAVE_REQUEST ="PUT_LEAVE_REQUEST";
export const PUT_LEAVE_SUCCESS ="PUT_LEAVE_SUCCESS";
export const PUT_LEAVE_ERROR ="PUT_LEAVE_ERROR";

//DELETE SINGLE TRAINER

export const DELETE_LEAVE_REQUEST="DELETE_LEAVE_REQUEST";
export const DELETE_LEAVE_SUCCESS="DELETE_LEAVE_SUCCESS";
export const DELETE_LEAVE_ERROR="DELETE_LEAVE_ERROR";