//GET ALL USER
export const GET_USER_REQUEST = "USER_REQUEST";
export const GET_USER_SUCCESS = "USER_SUCCESS";
export const GET_USER_ERROR = "USER_ERROR";



//GET SINGLE USER

export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST';
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS';
export const GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR';




//POST SINGLE USER
export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_ERROR = "POST_USER_ERROR";



//PUT SINGLE USER
export const PUT_USER_REQUEST = "PUT_USER_REQUEST";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_ERROR = "PUT_USER_ERROR";




//DELETE SINGLE USER
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

//Logout

export const LOGOUT = "LOGOUT"

