//GET ALL BRANCHES
export const GET_BRANCHES_REQUEST = "BRANCHES_REQUEST";
export const GET_BRANCHES_SUCCESS = "BRANCHES_SUCCESS";
export const GET_BRANCHES_ERROR = "BRANCHES_ERROR";



//GET SINGLE BRANCH

export const GET_SINGLE_BRANCH_REQUEST = 'GET_SINGLE_BRANCH_REQUEST';
export const GET_SINGLE_BRANCH_SUCCESS = 'GET_SINGLE_BRANCH_SUCCESS';
export const GET_SINGLE_BRANCH_ERROR = 'GET_SINGLE_BRANCH_ERROR';




//POST SINGLE BRANCH
export const POST_BRANCH_REQUEST = "POST_BRANCH_REQUEST";
export const POST_BRANCH_SUCCESS = "POST_BRANCH_SUCCESS";
export const POST_BRANCH_ERROR = "POST_BRANCH_ERROR";



//PUT SINGLE BRANCH
export const PUT_BRANCH_REQUEST = "PUT_BRANCH_REQUEST";
export const PUT_BRANCH_SUCCESS = "PUT_BRANCH_SUCCESS";
export const PUT_BRANCH_ERROR = "PUT_BRANCH_ERROR";




//DELETE SINGLE BRANCH
export const DELETE_BRANCH_REQUEST = "DELETE_BRANCH_REQUEST";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_ERROR = "DELETE_BRANCH_ERROR";



