//GET ALL TRAINERLEAVES
export const GET_TRAINERLEAVES_REQUEST = "GET_TRAINERLEAVES_REQUEST";
export const GET_TRAINERLEAVES_SUCCESS = "GET_TRAINERLEAVES_SUCCESS";
export const GET_TRAINERLEAVES_ERROR = "GET_TRAINERLEAVES_ERROR";

//GET SINGLE TRAINERLEAVE 

export const GET_SINGLE_TRAINERLEAVE_REQUEST ="GET_SINGLE_TRAINERLEAVE_REQUEST";
export const GET_SINGLE_TRAINERLEAVE_SUCCESS ="GET_SINGLE_TRAINERLEAVE_SUCCESS";
export const GET_SINGLE_TRAINERLEAVE_ERROR ="GET_SINGLE_TRAINERLEAVE_ERROR";

//POST SINGLE TRAINERLEAVES

export const POST_TRAINERLEAVE_REQUEST ="POST_TRAINERLEAVE_REQUEST";
export const POST_TRAINERLEAVE_SUCCESS ="POST_TRAINERLEAVE_SUCCESS";
export const POST_TRAINERLEAVE_ERROR ="POST_TRAINERLEAVE_ERROR";

//PUT SINGLE TRAINERLEAVES

export const PUT_TRAINERLEAVE_REQUEST ="PUT_TRAINERLEAVE_REQUEST";
export const PUT_TRAINERLEAVE_SUCCESS ="PUT_TRAINERLEAVE_SUCCESS";
export const PUT_TRAINERLEAVE_ERROR ="PUT_TRAINERLEAVE_ERROR";

//DELETE SINGLE TRAINERLEAVES

export const DELETE_TRAINERLEAVE_REQUEST="DELETE_TRAINERLEAVE_REQUEST";
export const DELETE_TRAINERLEAVE_SUCCESS="DELETE_TRAINERLEAVE_SUCCESS";
export const DELETE_TRAINERLEAVE_ERROR="DELETE_TRAINERLEAVE_ERROR";