//GET ALL BATCHES
export const GET_BATCHES_REQUEST="BATCHES_REQUEST";//get batches
export const GET_BATCHES_SUCCESS="BATCHES_SUCCESS";//dispatch batches
export const GET_BATCHES_ERROR="BATCHES_ERROR";//error batches
//GET SINGLE BATCH
export const GET_BATCH_REQUEST="BATCH_REQUEST";
export const GET_BATCH_SUCCESS="BATCH_SUCCESS";
export const GET_BATCH_ERROR="BATCH_ERROR";
//GET SINGLE BRANCH
export const GET_SINGLE_BATCH_REQUEST = 'GET_SINGLE_BRANCH_REQUEST';
export const GET_SINGLE_BATCH_SUCCESS = 'GET_SINGLE_BRANCH_SUCCESS';
export const GET_SINGLE_BATCH_ERROR = 'GET_SINGLE_BRANCH_ERROR';
//POST SINGLE BATCH
export const POST_BATCH_REQUEST="POST_BATCH_REQUEST";
export const POST_BATCH_SUCCESS=" POST_BATCH_SUCCESS";
export const POST_BATCH_ERROR="POST_BATCH_ERROR";
//PUT SINGLE BATCH
export const PUT_BATCH_REQUEST="PUT_BATCH_REQUEST";
export const PUT_BATCH_SUCCESS=" PUT_BATCH_SUCCESS";
export const PUT_BATCH_ERROR="PUT_BATCH_ERROR";
 //DELETE SINGLE BATCH
export const DELETE_BATCH_REQUEST="DELETE_BATCH_REQUEST";
export const DELETE_BATCH_SUCCESS=" DELETE_BATCH_SUCCESS";
export const DELETE_BATCH_ERROR="DELETE_BATCH_ERROR";



